org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

edwin_gt_config_url="a8+MUVrAPZ/Cvu0uuZSzCdZH1pWlg6epn3roSmM1gmHQpsX1cYtGBdrzMHAb7pjMNTgCeTc6LVp7/MRCxiMlAU5YQ9h20ezyKF/m6ZMpb5+falPw1dLB1jkU6Jrd05QuiLVn1R15C8AS/drJQJ94gqlNlkVOEXZw4XdXVZp4ba8Fl5hWO8Jx+80IPG+4KY1x4/LXTHFt3wJn6rsEQwIMWiRFi0DrH0x4qaQJ8fs4M80EbQiUk8KHXtKCtBEpPq+pBuVl/Mvd24hOJVSzPLckfV334bT1TozbXhul33PA/+aqFkkn2OplCHGh7kLsF5vp"